### PR TITLE
refactor: consolidate duplicate logic and adopt native/shared helpers

### PR DESCRIPTION
**Pull request by LionSR**
## Summary

A scheduled sweep of the codebase for consolidation opportunities: duplicate logic across 2+ call sites, and hand-rolled implementations of things a native method or an existing shared helper already covers. Four parallel scans (`src/agent`, `src/tools`/`src/model`/`src/utils`/etc., `packages/extension`, `packages/cli`/`packages/desktop`/`packages/trace-viewer`) turned up eight concrete findings, all applied here. `src/agent/**` came back clean — no findings survived the "real, multi-call-site impact" bar there; that scope is excluded from this PR.

- Add `groupBy()` to `@utils/core` and use it at 5 hand-rolled `Map` bucketing sites, including `groupPendingApprovalsByRow` in `packages/cli/src/chat/tui/appInteractionPolicy.ts` (rebased onto main's own `pendingApprovalsForRows` extraction — see rebase note below), `state/streamViews.ts`, `panes/StaticConversationTranscript.tsx`, and `packages/desktop/src/renderer/desktopCommandPalette.ts`.
- `packages/desktop/src/desktopTaskShell.ts`: drop the local `clamp()` reimplementation, use the shared one from `@utils/core` (already used elsewhere in the same package).
- `packages/cli/src/chat/tui/state/subscribeRuntimeHost.ts`: replace the hand-rolled array-equality check (`sameStringList`) with `node:util`'s `isDeepStrictEqual`, matching the existing pattern in the sibling file `subscribeStreamLog.ts`.
- `packages/extension/src/commands/latex/{figCommands.ts,imageCommands.ts}`: replace manual `.slice(0, 100) + '...'` truncation with the existing grapheme-aware `truncateWithEllipsis()`. **Minor observable change** (flagged by review): the shared helper uses a single-character Unicode ellipsis (`…`) instead of three ASCII dots, and only appends it when the string is actually truncated (the old code appended `...` unconditionally, even to short strings). For `figCommands.ts` it also avoids splitting a multi-byte grapheme mid-truncation. Both are improvements, not regressions, but they are technically observable output changes in a debug log / quick-pick detail string — not pure no-ops.
- Extract `raceWithTimeout()` (event-vs-timeout race with disposal/cleanup bookkeeping) into `packages/extension/src/frontend/vscode/raceWithTimeout.ts`. It previously existed as an unexported local in `setupTerminalRunner.ts` while `vscodeDiagnostics.ts` reimplemented the same settle/cleanup logic from scratch; both now share it. (Two other sites flagged by the scan — `VscodeDiffViewHost.ts` and `SupabaseAuthProvider.ts` — do extra work in their timeout branch that doesn't fit this shape cleanly, so they were left alone rather than forced into it.)
- `src/tools/approval/{bashApproval.ts,toolEditApproval.ts}`: factor the identical session-bypass get/set helper pairs into one parametrized `createSessionBypassAccessors()` in a new `sessionBypassAccessors.ts`. Public export names/signatures are unchanged.
- `src/utils/system/execUtils.ts`: dedupe the identical catch-block error-logging in `executeCommand`/`executeCommandSync` into `logExecutionErrorAndBuildResult()`.
- `src/tools/TextEditorTool.ts`: dedupe the identical undo-history `afterWrite` callback in `strReplace`/`insert` into `undoHistoryAfterWrite()`.

All behavior is preserved except the truncation-formatting nuance called out above (debug-log / quick-pick-detail cosmetics only, not functional).

**Rebase note:** this branch was rebased onto `main` after `main`'s own module-level simplification sweep (#9473) landed and independently touched 5 of the same files — including a parallel extraction of the `pendingApprovalsForRows` grouping (moved to `groupPendingApprovalsByRow` in `appInteractionPolicy.ts`) and a parallel merge of the two array-equality checks in `subscribeRuntimeHost.ts` (into `sameStringList`). Resolved by keeping `main`'s structure and layering this PR's native-method wins on top: `groupPendingApprovalsByRow` now uses `groupBy()` internally, and `sameStringList` now uses `isDeepStrictEqual` internally. That same `main` commit also fixed the pre-existing `@google/genai` type error that was failing `static checks` on this PR before the rebase.

## Issue acceptance gates

Not issue-driven — a proactive consolidation sweep. No specific issue/gates to satisfy.

## Single source of truth

- Map-bucketing: `groupBy()` in `src/utils/core/index.ts`.
- VS Code event/timeout race: `raceWithTimeout()` in `packages/extension/src/frontend/vscode/raceWithTimeout.ts`.
- Approval session-bypass get/set: `createSessionBypassAccessors()` in `src/tools/approval/sessionBypassAccessors.ts`.
- Command-execution error logging: `logExecutionErrorAndBuildResult()` in `src/utils/system/execUtils.ts`.
- Undo-history bookkeeping for text-editor writes: `TextEditorTool.undoHistoryAfterWrite()`.
- Approval-row grouping: `groupPendingApprovalsByRow()` in `packages/cli/src/chat/tui/appInteractionPolicy.ts`.
- Array-equality check for run-config files / queued follow-ups: `sameStringList()` in `subscribeRuntimeHost.ts`.

## Duplication and abstraction budget

Removed: 5 hand-rolled group-by accumulators, 1 duplicated (2-copy) event/timeout race helper, 2 identical approval-bypass accessor pairs, 1 duplicated catch-block, 1 duplicated `afterWrite` callback, 2 manual truncations, 1 duplicated `clamp()`, 2 hand-rolled array-equality checks (now 1 shared helper, native-backed). Each new helper (`groupBy`, `raceWithTimeout`, `createSessionBypassAccessors`, `logExecutionErrorAndBuildResult`, `undoHistoryAfterWrite`) has 2+ real call sites in this same PR and owns exactly one invariant (bucket-by-key order, dispose-on-settle race semantics, bypass read/write, error-log-then-build-result, write-then-record-undo-baseline). No pass-through wrappers added.

## Net elements (R6)

17 files changed, +211/-176 (net +35 lines, but two of those files are new small single-purpose modules; the touched call sites shrank overall). New exported symbols: `groupBy`, `raceWithTimeout`, `Raced`, `createSessionBypassAccessors` — each with 2+ consumers added in this PR. `setBashApprovalSessionBypass`, `isBashApprovalBypassedForStream`, `setToolEditApprovalSessionBypass`, `isApprovalBypassedForStream` keep their exported names/signatures, now backed by the shared factory instead of duplicated bodies.

## Consumer counts (R8)

n/a — no emit path or export was deleted or re-routed; the four approval-bypass export names are preserved with identical signatures.

## Host impact

Extension: `raceWithTimeout` consolidation (terminal runner + diagnostics wait); truncation fix in fig/image commands.

Desktop: `groupBy`/`clamp` consolidation in the command palette and task-shell reducer.

CLI: `groupBy` consolidation across App.tsx/appInteractionPolicy.ts/streamViews/StaticConversationTranscript; `isDeepStrictEqual` in subscribeRuntimeHost.

## Scheduled refactoring

None — `VscodeDiffViewHost.ts`'s reveal-with-retry and `SupabaseAuthProvider.ts`'s cancellation-token-aware wait were deliberately left out of the `raceWithTimeout` consolidation (different timeout-branch behavior); no follow-up filed since they're not a clean fit for the current helper shape.

## Validation

- `npx tsc --noEmit` (root) and every workspace package's typecheck (`cli`, `desktop`, `trace-viewer`, `texra`/extension): clean, zero errors, after rebasing onto `main` (the pre-existing `@google/genai` type error that predated this PR is now fixed upstream).
- `npm test`: 799 test files / 7981 tests passed (1 file / 9 tests skipped, pre-existing).
- `npm run lint`: clean.
- `npm run check:dead-code-ratchet`: no new unused files/exports/types (17 findings, same as baseline).
- `prettier --check`: clean.
- Automated `deepseekproT` review: passes, all eight consolidations verified semantically equivalent; the truncation nuance above is the one finding, now reflected here.

---
_Generated by [Claude Code](https://claude.ai/code/session_01FEDFapqtrMxiYoiQmuS4mM)_

### CODE REVIEW

**Comment by LionSR** [comment]
`static checks (linux)` is red on `src/agent/modelHandlers/google/modelHandlerGoogleInteractions.ts(2036,7): error TS2353: Object literal may only specify known properties, and 'temperature' does not exist in type 'GenerationConfig_2'.` — that file isn't touched by this PR. Confirmed via `git stash` that the same error reproduces identically on `main` at the base commit (`4b3e8e6`), i.e. a pre-existing `@google/genai` SDK type mismatch, not a regression from this diff. Will re-run this branch against `main` once that's fixed upstream; not fixing it here since it's out of scope for a consolidation-only PR.


---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by LionSR** [comment]
need to rebase

**Comment by LionSR** [comment]
Rebased onto `main` (`3c50411`), which also fixes the pre-existing `static checks` failure flagged above — that commit's `fix(google): drop temperature from Interactions generation_config` removes the exact `GenerationConfig_2` type mismatch. Full `tsc --noEmit` is now clean with zero errors.

`main`'s own module-level simplification sweep (#9473) independently touched 5 of the files this PR modifies, including a parallel extraction of the exact `pendingApprovalsForRows` grouping this PR was consolidating (moved to `groupPendingApprovalsByRow` in `appInteractionPolicy.ts`) and a parallel merge of the two hand-rolled array-equality checks in `subscribeRuntimeHost.ts` (into `sameStringList`). Resolved by taking `main`'s extraction/structure and layering this PR's native-method wins on top of it:

- `groupPendingApprovalsByRow` (now in `appInteractionPolicy.ts`) uses `groupBy()` internally instead of the hand-rolled `Map.get() ?? [] / push` idiom.
- `sameStringList` (now the single helper backing both call sites) uses `isDeepStrictEqual` instead of the hand-rolled length+`every` check.
- `desktopTaskShell.ts`: merged import list (kept `main`'s new `getBasename`/`DesktopRoute` alongside this PR's `clamp`).

Re-verified after rebase: `tsc --noEmit` (root + every workspace package) clean, `npm test` 799 files / 7981 tests passed (1 file / 9 tests skipped, pre-existing), `npm run lint` clean, `npm run check:dead-code-ratchet` clean (17 baseline, no new), `prettier --check` clean. Force-pushed.


---
_Generated by [Claude Code](https://claude.ai/code)_
